export const DEFAULT_LIMIT = 10;

export const FETCH_TAGS = 'FETCH_TAGS';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';
export const FETCH_ARTICLES_OFFSET = 'FETCH_ARTICLES_OFFSET';
export const FETCH_ARTICLES_OFFSET_SUCCESS = 'FETCH_ARTICLES_OFFSET_SUCCESS';
export const FETCH_ARTICLES_OFFSET_FAILURE = 'FETCH_ARTICLES_OFFSET_FAILURE';